# Generated by Django 4.2.4 on 2023-10-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('public_key', models.CharField(max_length=100)),
            ],
        ),
    ]
